### ISSUE TITLE
Error parsing enum values with numbers in them.

### ISSUE THREAD

**Issue by hasenbanck** [madwareru/intellij-ron-remix#14]
Given the following ron file:

```
Configuration(
    paths: Paths(
        data: "data"
    ),
    video: Video(
        // Video mode options: window, fullscreen, borderless
        mode: window,
        // Refresh rate used in fullscreen mode
        refresh_rate: 60,
        // Vertical sync
        vsync: true,
        // Sets the fullscreen or window resolution. Ignored in borderless mode.
        width: 1920,
        height: 1080,
        // Vertical FOV (float)
        fovy: 70,
        // Anisotropic texture filtering options: off, x1, x2, x3, x4, x8, x16
        anisotropic_filtering: x16,
    ),
    force_level: Some("level0")
)
````

I get the following error for the anisotropic_filtering enum value (x16): 

```
RONTokenType."(, RONTokenType.) or RONTokenType. expected, got '16'.
```

The file can properly parsed by the ron deserializer.

**Comment by madwareru** [comment]
Hi, Nils! Thanks for an issue, indeed it looks to be broken right now. I'll do a fix and release it with a next version of a plugin, I'll inform you here when it would be available in a market

**Comment by madwareru** [comment]
I fixed it and you can download it from here now:
https://github.com/madwareru/intellij-ron-remix/releases/tag/v0.2.1
 
It's also right now on a moderation in a marketplace as well

**Comment by madwareru** [comment]
@hasenbanck a new version should be available today, stay tuned! I'll inform you as soon as it will be ready to download from a marketplace, and if it suits you, I'll close an issue

**Comment by hasenbanck** [comment]
Okay, the update just poped up in Clion, so that I could test the changes. The bug is fixed on my side. Thank you very much.
