### ISSUE TITLE
Update for new intellij 2022 Version planed?

### ISSUE THREAD

**Issue by sggt** [madwareru/intellij-ron-remix#23]
As the topic says, are there any plans to update the plugin or is it abandoned?

**Comment by madwareru** [comment]
Hi @sggt, thanks for the question!
Yeah, there are plans. A plugin is not abandoned. I was a bit busy, but I will update plugin in nearest future

**Comment by madwareru** [comment]
The plugin now is in moderation in a marketplace, but you can download it from releases and install it manually from a disk

**Comment by madwareru** [comment]
Done, 2022 version support is on marketplace :)
