### ISSUE TITLE
IntelliJ IDEA 2022.3 compatibility

### ISSUE THREAD

**Issue by enygmator** [madwareru/intellij-ron-remix#27]
**Not compatible with the version of your running IDE (IntelliJ IDEA 2022.3)** - error shows up in marketplace

I'm not sure if this is where I file the issue, but since this repo seems to be keeping compatibility with the latest version of IntelliJ, I'm filing the issue here.

**Comment by madwareru** [comment]
Hi! Yeah, I'm aware of it, but thanks anyway :)
I will update plugin in a near time

**Comment by enygmator** [comment]
alright. Thanks a lot!

**Comment by madwareru** [comment]
The new version of a plugin will be on review now and should meet marketplace in a day or two
