### ISSUE TITLE
Map gives false error when using a struct as a key instead of a String

### ISSUE THREAD

**Issue by NoahShomette** [madwareru/intellij-ron-remix#33]
Heres the relevent RON set: 
```
(
 tile_object_stacks: (
    tile_object_stacks:{
       (name:"Units"): (
           current_count: 0,
           max_count: 1
           )
      }
 ), 
)
```

I get this error from the plugin at the opening ( for the key value (name:"Units")
> map key or RONTokenType.} expected, got '('

Despite the error the file does load correctly into my program.

**Comment by madwareru** [comment]
Yeah it's known issue, the plugin does not support objects and tupples as keys at the moment.
